<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap — Forest Gate Trails</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #333333;
            background: #ffffff;
            padding: 24px 32px;
          }
          #header {
            margin-bottom: 24px;
          }
          h1 {
            font-size: 24px;
            font-weight: 700;
            color: #111111;
            margin-bottom: 8px;
          }
          p.intro {
            font-size: 13px;
            color: #666666;
            line-height: 1.6;
          }
          p.intro a {
            color: #0066cc;
            text-decoration: none;
          }
          p.intro a:hover {
            text-decoration: underline;
          }
          p.stats {
            font-size: 13px;
            color: #444444;
            margin-top: 8px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            margin-top: 16px;
          }
          th {
            text-align: left;
            padding: 10px 14px;
            font-weight: 700;
            color: #444444;
            border-bottom: 2px solid #b5b5b5;
            background-color: #ffffff;
          }
          td {
            padding: 9px 14px;
            color: #222222;
            vertical-align: middle;
          }
          tr:nth-child(even) {
            background-color: #f2f2f2;
          }
          tr:hover {
            background-color: #e8eff7;
          }
          td.url a {
            color: #111111;
            text-decoration: none;
            word-break: break-all;
          }
          td.url a:hover {
            color: #0066cc;
            text-decoration: underline;
          }
          .col-url {
            width: 65%;
          }
          .col-images {
            width: 10%;
          }
          .col-lastmod {
            width: 25%;
          }
        </style>
      </head>
      <body>
        <div id="header">
          <h1>XML Sitemap</h1>
          <p class="intro">
            Generated by <strong>Forest Gate Trails</strong>. This XML sitemap is indexed by Google, Bing, and other search engines.<br/>
            You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener noreferrer">sitemaps.org</a>.
          </p>
          <p class="stats">
            Number of URLs in this sitemap: <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong>
          </p>
        </div>

        <table>
          <thead>
            <tr>
              <th class="col-url">URL</th>
              <th class="col-images">Images</th>
              <th class="col-lastmod">Last Mod.</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td class="col-url url">
                  <a>
                    <xsl:attribute name="href">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:attribute>
                    <xsl:value-of select="sitemap:loc"/>
                  </a>
                </td>
                <td class="col-images">
                  <xsl:value-of select="count(image:image)"/>
                </td>
                <td class="col-lastmod">
                  <xsl:value-of select="sitemap:lastmod"/>
                </td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
