export const RETREATS_DATA = [
  {
    id: 'the-forest-retreat',
    slug: 'the-forest-retreat',
    href: '/the-forest-retreat',
    name: 'The Forest Retreat',
    tagline: 'Secluded Luxury Mountain Sanctuary & Pine Forest Wellness',
    badge: 'Flagship Sanctuary',
    elevation: '4,350 Ft.',
    temperature: '18°C - 24°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/YOUR SANCTUARY IN THE MOPUNTAINS.png',
    summary:
      'Our signature hilltop sanctuary perched high above the clouds in Village Tandeo. Surrounded by centuries-old pine canopies, private stone firepits, and panoramic valley sunrises.',
    overview:
      'The Forest Retreat represents the pinnacle of eco-conscious hospitality at The Forest Gate. Architecturally sculpted into the gentle mountain contours of Morni Hills, this flagship sanctuary harmonizes raw mountain stone, reclaimed teak, and floor-to-ceiling glass to dissolve the boundary between indoors and the wilderness.',
    highlights: [
      { label: '4,350 Ft. Elevation', sub: 'Panoramic Shivalik cloud inversions' },
      { label: 'Private Firepits', sub: 'Under a billion starlit sky' },
      { label: 'Forest Bathing Trails', sub: 'Guided Shinrin-yoku walks' },
      { label: 'Farm-to-Fork Cuisine', sub: 'Organic mountain harvests' },
    ],
    gallery: [
      '/assets/images/forestgate-image/YOUR SANCTUARY IN THE MOPUNTAINS.png',
      '/assets/images/forestgate-image/PROPERTTY.png',
      '/assets/images/forestgate-image/RIVER VIEW.jpeg',
      '/assets/images/forestgate-image/ROOMS.jpeg',
    ],
    features: [
      'Private Heated Stone Jacuzzi Deck',
      'Panoramic 270° Mountain Horizon',
      'Dedicated Forest Butler & Naturalist',
      'Signature Open-Air Stargazing Cinema',
      'Artisanal Fireplace in Every Suite',
      'High-Speed Satellite Connectivity',
    ],
    experiences: [
      {
        id: 'shinrin-yoku',
        title: 'Guided Shinrin-Yoku & Pine Meditation',
        tag: 'Wellness',
        description:
          'Step into ancient pine groves with certified naturalists. Inhale phytoncides that awaken immune vitality while practicing guided breathwork above misty valleys.',
        image: '/assets/images/forestgate-image/mountain trekking.jpg',
        duration: '2 Hours',
        timing: 'Sunrise (6:30 AM)',
      },
      {
        id: 'sunset-bonfire',
        title: 'Sunset Acoustic Bonfire & Barbecue',
        tag: 'Evening Ritual',
        description:
          'As twilight blankets the Shivalik peaks, gather by your private stone pit with live acoustic melodies, smoky tandoori delicacies, and spiced hill cider.',
        image: '/assets/images/forestgate-image/Bonfire.jpg',
        duration: 'Evening Session',
        timing: '7:30 PM Onwards',
      },
      {
        id: 'river-trek',
        title: 'Ghaggar Riverbed Safari & Stream Picnic',
        tag: 'Adventure',
        description:
          'Descend gentle pine trails to crystal mountain streams. Unpack chef-curated picnic baskets, artisanal sourdough, and crisp wild-berry coolers on sun-warmed boulders.',
        image: '/assets/images/forestgate-image/RIVER VIEW.jpeg',
        duration: 'Half Day',
        timing: '10:00 AM - 2:00 PM',
      },
      {
        id: 'open-cinema',
        title: 'Starlight Forest Cinema Under The Pines',
        tag: 'Entertainment',
        description:
          'Curl up with cashmere blankets on memory-foam daybeds under pine silhouettes for timeless cinema accompanied by hand-roasted s’mores.',
        image: '/assets/images/forestgate-image/Mini-Cinema-Home-Theater.png',
        duration: 'Night Session',
        timing: '8:30 PM Onwards',
      },
    ],
    accommodations: [
      {
        name: 'The Royal Pine Villa',
        type: 'Private 2-Bedroom Chalet',
        size: '1,450 sq.ft.',
        occupancy: 'Up to 4 Adults + 2 Kids',
        price: '₹18,500',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Split-level cedar timber villa featuring an open-hearth fireplace, floor-to-ceiling forest glass, and a wrap-around teak veranda overlooking the pine valley.',
        amenities: ['Private Stone Firepit', 'Jacuzzi with View', 'King Featherbed', 'Espresso Bar', '24/7 Butler Call'],
      },
      {
        name: 'The Valley Vista Suite',
        type: 'Elevated Romantic Suite',
        size: '850 sq.ft.',
        occupancy: '2 Adults',
        price: '₹14,000',
        image: '/assets/images/forestgate-image/ROOM 1.jpeg',
        desc: 'Designed for intimate getaways, boasting an infinity daybed facing the morning sunrise, deep soaking tub, and uninterrupted mountain horizons.',
        amenities: ['Private Sunrise Balcony', 'Deep Soaking Tub', 'Pillow Menu', 'Bose Surround Sound', 'High-Speed Wi-Fi'],
      },
    ],
    faqs: [
      {
        q: 'What makes The Forest Retreat different from other resort stays?',
        a: 'The Forest Retreat is our highest-elevation flagship sanctuary. It offers unparalleled privacy, bespoke forest concierge service, private firepits on every villa deck, and total immersion in ancient pine groves far removed from noisy tourist corridors.',
      },
      {
        q: 'How far is The Forest Retreat from Chandigarh and Panchkula?',
        a: 'The Forest Retreat is situated in Village Tandeo, Morni Hills, approximately a scenic 60 to 75-minute drive (42 km) from Chandigarh and Panchkula through smooth, winding hill roads.',
      },
      {
        q: 'Can we book The Forest Retreat for private celebrations or corporate offsites?',
        a: 'Yes, we offer complete sanctuary buyouts for curated family gatherings, intimate weddings, and executive leadership retreats with customized chef menus and private event staging.',
      },
    ],
  },
  {
    id: 'forest-haven',
    slug: 'forest-haven',
    href: '/forest-haven',
    name: 'Forest Haven',
    tagline: 'Eco-Luxury Forest Villas, Peaceful Birdwatching & Creek Trails',
    badge: 'Eco-Luxury Haven',
    elevation: '4,280 Ft.',
    temperature: '19°C - 25°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/PROPERTTY.png',
    summary:
      'A tranquil haven tucked into lush oak and deodar groves. Ideal for families and couples seeking slow-living, soothing mountain breezes, and birdsong.',
    overview:
      'Forest Haven was conceived as a sanctuary of pure quietude. Perched alongside gentle mountain creeks and terraced fruit orchards, it offers sunlit verandas, handcrafted wooden interiors, and endless birdsong. Over 60 Himalayan bird species have been recorded in Haven’s private tree canopy.',
    highlights: [
      { label: '4,280 Ft. Elevation', sub: 'Gentle temperate valley breezes' },
      { label: '60+ Bird Species', sub: 'Ornithologist guided walks' },
      { label: 'Creek-Side Decks', sub: 'Soothing mountain water sounds' },
      { label: 'Family & Pet Welcoming', sub: 'Expansive private lawns' },
    ],
    gallery: [
      '/assets/images/forestgate-image/PROPERTTY.png',
      '/assets/images/forestgate-image/BIRD WATCHING.png',
      '/assets/images/forestgate-image/Family & Pet Friendly.jpg',
      '/assets/images/forestgate-image/ROOM 1.jpeg',
    ],
    features: [
      'Expansive Private Garden & Hammock Lawns',
      'Bird Sanctuary Viewing Observatory Decks',
      'Heated Outdoor Dining Pavilions',
      'Pet-Friendly Enclosed Cottage Yards',
      'Eco-Friendly Solar & Spring Water Amenities',
      'Library & Herbal Tea Lounge',
    ],
    experiences: [
      {
        id: 'birdwatching',
        title: 'Himalayan Dawn Birding Safari',
        tag: 'Nature',
        description:
          'Armed with high-definition binoculars and field guides, walk with our resident naturalist to spot red-billed blue magpies, barbets, and paradise flycatchers.',
        image: '/assets/images/forestgate-image/BIRD WATCHING.png',
        duration: '1.5 Hours',
        timing: '7:00 AM Daily',
      },
      {
        id: 'creek-trail',
        title: 'Secret Creek Trail & Herbal Tea Tasting',
        tag: 'Exploration',
        description:
          'Stroll down paved stone paths to hidden freshwater streams where wild mint grows in abundance, culminating in a fresh hill-herb tea tasting.',
        image: '/assets/images/forestgate-image/RIVER VIEW.jpeg',
        duration: '2 Hours',
        timing: '11:00 AM & 3:30 PM',
      },
      {
        id: 'family-bonfire',
        title: 'Family Storytelling & Marshmallow Roast',
        tag: 'Gathering',
        description:
          'An intimate bonfire setup surrounded by fairy lights and mountain blossoms, perfect for multi-generational conversations and campfire games.',
        image: '/assets/images/forestgate-image/Bonfire.jpg',
        duration: 'Evening Session',
        timing: '7:00 PM Onwards',
      },
      {
        id: 'lawn-games',
        title: 'High-Altitude Lawn Croquet & Bocce',
        tag: 'Leisure',
        description:
          'Unwind on velvety green lawns with gentle outdoor games, handcrafted iced lemonades, and uninterrupted mountain panoramas.',
        image: '/assets/images/forestgate-image/Indoor&OutdoorGames.png',
        duration: 'All Day',
        timing: 'Anytime',
      },
    ],
    accommodations: [
      {
        name: 'The Haven Garden Cottage',
        type: 'Pet-Friendly Family Cottage',
        size: '1,100 sq.ft.',
        occupancy: 'Up to 4 Adults',
        price: '₹16,000',
        image: '/assets/images/forestgate-image/ROOM 1.jpeg',
        desc: 'Surrounded by blossoming hill shrubs with a fenced private lawn, sunroom breakfast nook, and cozy timber-clad master bedroom.',
        amenities: ['Fenced Private Lawn', 'Pet Welcome Kit', 'Sunroom Reading Nook', 'Kitchenette & Mini Bar', 'Fireplace'],
      },
      {
        name: 'The Canopy Serenity Room',
        type: 'Couples Forest Hideaway',
        size: '720 sq.ft.',
        occupancy: '2 Adults',
        price: '₹12,500',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Tucked into the treetop canopy with panoramic bay windows, plush rocking chairs, and an open-sky glass shower.',
        amenities: ['Treetop Bay Windows', 'Glass Sky Shower', 'Organic Herb Toiletries', 'Wi-Fi', 'Breakfast in Bed Option'],
      },
    ],
    faqs: [
      {
        q: 'Is Forest Haven pet-friendly?',
        a: 'Yes! Forest Haven features dedicated pet-welcoming ground-level cottages with enclosed lawns, fresh pet bedding, and tailored natural meal bowls upon request.',
      },
      {
        q: 'Is Forest Haven suitable for elderly family members?',
        a: 'Absolutely. Forest Haven is thoughtfully designed with step-free entry ramps, gentle gravel paths, ground-floor luxury cottages, and convenient golf-cart transit on property.',
      },
      {
        q: 'What bird species can we see around Forest Haven?',
        a: 'The property regularly witnesses Himalayan Bulbul, Asian Paradise Flycatcher, Great Barbet, Black Francolin, and Khalij Pheasant right from private balconies.',
      },
    ],
  },
  {
    id: 'whispering-woods',
    slug: 'whispering-woods',
    href: '/whispering-woods',
    name: 'Whispering Woods',
    tagline: 'Canopy Treehouses, Pine Breeze Meditation & Starlit Nights',
    badge: 'Canopy & Treehouse Enclave',
    elevation: '4,410 Ft.',
    temperature: '17°C - 23°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/FORNT VIEW PROPERTY.png',
    summary:
      'Perched high in the ancient pine canopy where mountain winds whisper tales of old. Featuring architectural treehouse chalets and glass skylights.',
    overview:
      'Whispering Woods is our most romantic, suspended-in-the-clouds enclave. Built with sustainable pine timber and elevated steel stilts, each treehouse suite floats above the forest floor, allowing cool Shivalik breezes to circulate freely and pine aromas to lull you into supreme calm.',
    highlights: [
      { label: '4,410 Ft. Elevation', sub: 'Highest enclave ridge' },
      { label: 'Architectural Treehouses', sub: 'Hovering 30 ft above the ground' },
      { label: 'Skylight Stargazing', sub: 'Gaze into deep cosmos from bed' },
      { label: 'Acoustic Forest Nights', sub: 'Firepits with live folk violin & flute' },
    ],
    gallery: [
      '/assets/images/forestgate-image/FORNT VIEW PROPERTY.png',
      '/assets/images/forestgate-image/mountain trekking.jpg',
      '/assets/images/forestgate-image/Bonfire.jpg',
      '/assets/images/forestgate-image/Mini-Cinema-Home-Theater.png',
    ],
    features: [
      'Suspended Skywalk Connecting Treetop Decks',
      'Glass Roof Stargazing Bedrooms',
      'Private High-Altitude Cedar Saunas',
      'Acoustic Firepit Amphitheater',
      'Forest Soundscape Meditation Pods',
      'Bespoke Candlelight Treetop Dining',
    ],
    experiences: [
      {
        id: 'skywalk-trek',
        title: 'Canopy Skywalk & Pine Needle Trail',
        tag: 'Scenic Walk',
        description:
          'Walk across suspended wooden skywalks connecting centuries-old pine canopies with breathtaking panoramic views of the Sirmaur valley.',
        image: '/assets/images/forestgate-image/mountain trekking.jpg',
        duration: '1.5 Hours',
        timing: 'Morning & Sunset',
      },
      {
        id: 'acoustic-night',
        title: 'Whispering Woods Acoustic Jam Session',
        tag: 'Music & Culture',
        description:
          'Warm your hands over glowing embers as local Pahadi and Sufi musicians weave gentle melodies that echo through the quiet woods.',
        image: '/assets/images/forestgate-image/Bonfire.jpg',
        duration: 'Evening Session',
        timing: '8:00 PM - 10:00 PM',
      },
      {
        id: 'canopy-dining',
        title: 'Candlelight Dinner Suspended in the Pines',
        tag: 'Romance',
        description:
          'A multi-course gourmet meal prepared by your personal chef on a secluded cantilevered wooden deck bathed in candlelight.',
        image: '/assets/images/forestgate-image/Open Sky Dining.png',
        duration: '2.5 Hours',
        timing: '8:00 PM Onwards',
      },
      {
        id: 'sunset-terrace',
        title: 'Ridge Sunset Aperitif Tasting',
        tag: 'Beverage',
        description:
          'Savor sparkling wines, artisanal mountain cheeses, and handcrafted non-alcoholic botanical elixirs as the sun dips below the horizon.',
        image: '/assets/images/forestgate-image/POOLSIDE SUNSET PARTY.jpg',
        duration: '1 Hour',
        timing: '5:30 PM - 6:30 PM',
      },
    ],
    accommodations: [
      {
        name: 'The Elevated Treehouse Villa',
        type: 'Suspended Luxury Chalet',
        size: '1,200 sq.ft.',
        occupancy: '2 to 3 Adults',
        price: '₹19,000',
        image: '/assets/images/forestgate-image/FORNT VIEW PROPERTY.png',
        desc: 'Elevated 30 feet above the forest floor with a 360-degree glass living pavilion, private cedar hot tub, and open stargazing roof hatch.',
        amenities: ['Private Cedar Hot Tub', 'Skylight Ceiling', 'Cantilevered Balcony', 'Nespresso Coffee Machine', 'Telescope'],
      },
      {
        name: 'The Pine Breeze Loft',
        type: 'Romantic Hideaway Suite',
        size: '800 sq.ft.',
        occupancy: '2 Adults',
        price: '₹15,000',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Split-level timber loft featuring an upstairs queen featherbed facing the sunrise ridge and a cozy downstairs fireplace lounge.',
        amenities: ['Split-Level Loft', 'Wood-Burning Stove', 'Valley Horizon Views', 'Complimentary Wine & Cheese', 'Wi-Fi'],
      },
    ],
    faqs: [
      {
        q: 'Are the treehouses at Whispering Woods safe and weather-proof?',
        a: 'Yes, every treehouse is engineered with industrial-grade steel anchors, double-insulated kiln-dried timber, and wind-resistant safety glass tested for all mountain seasons.',
      },
      {
        q: 'Is Whispering Woods recommended for honeymoons and couples?',
        a: 'It is our most requested enclave for anniversaries, proposals, and romantic milestones due to its seclusion, private hot tubs, and suspended candlelight dinners.',
      },
      {
        q: 'How does dining work in the elevated chalets?',
        a: 'You can dine at our central forest restaurant or order bespoke in-treehouse butler dining delivered straight to your cantilevered deck.',
      },
    ],
  },
  {
    id: 'wildwood-retreat',
    slug: 'wildwood_retreat',
    href: '/wildwood_retreat',
    name: 'Wildwood Retreat',
    tagline: 'Secluded Eco-Luxury Haven, Private Firepits & Valley Vistas',
    badge: 'Wilderness Luxury Enclave',
    elevation: '4,200 Ft.',
    temperature: '18°C - 24°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/RIVER VIEW.jpeg',
    summary:
      'Our celebrated low-density wilderness enclave at The Forest Gate. Featuring open-sky stargazing decks, riverside trails, and bespoke culinary journeys.',
    overview:
      'Wildwood Retreat is an ultra-exclusive enclave where untamed nature meets refined comfort. With private riverbed descents, open-sky cinema screenings, and personalized culinary journeys, Wildwood caters to the discerning traveler seeking stillness without sacrificing modern elegance.',
    highlights: [
      { label: '4,200 Ft. Elevation', sub: 'Crisp Shivalik mountain breeze' },
      { label: 'Virgin Pine Canopy', sub: 'Surrounded by tranquil Morni forests' },
      { label: 'Private Firepits', sub: 'Under a billion starlit sky' },
      { label: 'Dark-Sky Stargazing', sub: 'Zero light pollution zone' },
    ],
    gallery: [
      '/assets/images/forestgate-image/RIVER VIEW.jpeg',
      '/assets/images/forestgate-image/Bonfire.jpg',
      '/assets/images/forestgate-image/YOUR SANCTUARY IN THE MOPUNTAINS.png',
      '/assets/images/forestgate-image/ADVENTURE ACTIVITIES.jpg',
    ],
    features: [
      'Low-Density Wilderness Enclave with Total Privacy',
      'Personal Stargazing Decks with Celestron Telescopes',
      'Open-Sky Forest Cinema with S’mores Service',
      'Gourmet Chef Tailored Menus & In-Villa Dining',
      'Dedicated Wilderness Guide for Every Group',
      'Electric Cart & Mountain Bike Access',
    ],
    experiences: [
      {
        id: 'forest-bathing',
        title: 'Forest Bathing & Mindful Trails',
        tag: 'Wellness',
        description:
          'Immerse your senses in guided Shinrin-yoku walks along pine-scented forest paths, discovering hidden mountain flora and ancient stone trails.',
        image: '/assets/images/forestgate-image/mountain trekking.jpg',
        duration: '2 Hours',
        timing: 'Morning & Sunset',
      },
      {
        id: 'open-sky-cinema',
        title: 'Starlight Forest Cinema',
        tag: 'Entertainment',
        description:
          'Cozy movie screenings surrounded by pine silhouettes with warm throws, freshly roasted s’mores, and handcrafted hot cocoa.',
        image: '/assets/images/forestgate-image/Mini-Cinema-Home-Theater.png',
        duration: 'Evening Session',
        timing: '8:00 PM Onwards',
      },
      {
        id: 'river-picnic',
        title: 'Crystal Riverbed Picnics',
        tag: 'Signature',
        description:
          'Follow private descending trails to clear mountain streams with curated chef baskets, artisanal cheeses, and chilled hill-fruit juices.',
        image: '/assets/images/forestgate-image/RIVER VIEW.jpeg',
        duration: 'Half Day',
        timing: 'Midday Leisure',
      },
      {
        id: 'bonfire-music',
        title: 'Campfire & Acoustic Nights',
        tag: 'Evening Ritual',
        description:
          'Crackling pine cones, local folk acoustic guitarists, warm spiced glühwein, and storytelling around custom iron fire bowls under open skies.',
        image: '/assets/images/forestgate-image/Bonfire.jpg',
        duration: 'Night Session',
        timing: '7:30 PM Onwards',
      },
    ],
    accommodations: [
      {
        name: 'The Wildwood Canopy Villa',
        type: 'Private 2-Bedroom Chalet',
        size: '1,400 sq.ft.',
        occupancy: 'Up to 4 Adults + 2 Kids',
        price: '₹17,500',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Expansive wooden lodge with 180° valley views, sunken outdoor fire lounge, standalone clawfoot tub, and dedicated personal host.',
        amenities: ['Private Sunken Fire Lounge', 'Clawfoot Soaking Tub', 'Double Balcony Deck', 'Kitchenette & Mini Bar', 'Smart TV'],
      },
      {
        name: 'The Stargazer Pine Suite',
        type: 'Romantic Glass-Front Cottage',
        size: '750 sq.ft.',
        occupancy: '2 Adults',
        price: '₹13,500',
        image: '/assets/images/forestgate-image/ROOM 1.jpeg',
        desc: 'Cozy stone & cedar cottage featuring a plush king-size bed facing the Shivalik ridgeline, private telescope, and stone hearth fireplace.',
        amenities: ['Celestron Telescope', 'Stone Hearth Fireplace', 'Private Sunrise Veranda', 'High-Speed Wi-Fi', 'Complimentary Breakfast'],
      },
    ],
    faqs: [
      {
        q: 'What makes Wildwood Retreat different from regular resort stays?',
        a: 'Wildwood Retreat is our ultra-exclusive, low-density wilderness enclave at The Forest Gate. It offers total privacy, private firepits, dedicated personal hosts, custom nature trails, and unobstructed mountain vistas.',
      },
      {
        q: 'How do we reach Wildwood Retreat at The Forest Gate?',
        a: 'Wildwood Retreat is nestled in Village Tandeo, Morni Hills, Panchkula. It is easily accessible via a 1 hour 15-minute scenic mountain drive from Chandigarh International Airport.',
      },
      {
        q: 'What is the climate like at Wildwood Retreat?',
        a: 'Perched over 4,200 feet above sea level, Wildwood enjoys refreshingly cooler temperatures than the surrounding plains year-round.',
      },
    ],
  },
  {
    id: 'natures-gate',
    slug: 'natures-gate',
    href: '/natures-gate',
    name: 'Nature’s Gate',
    tagline: 'Mountain Gateway, Trekking Enclave & Riverside Flora Haven',
    badge: 'Adventure & Nature Gateway',
    elevation: '4,150 Ft.',
    temperature: '19°C - 26°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/TREKKING.png',
    summary:
      'The thrilling gateway to raw wilderness adventures in Morni Hills. From guided riverbed expeditions to cliffside yoga and off-road trail cycling.',
    overview:
      'Nature’s Gate is the energetic, expedition-ready sanctuary of The Forest Gate. Situated at the crossroads of ancient pilgrim footpaths and the Ghaggar river basin, it caters to thrill-seekers, adventurous families, and outdoor enthusiasts who love active days under the sun and lively poolside barbecues at dusk.',
    highlights: [
      { label: '4,150 Ft. Elevation', sub: 'Sun-drenched valley gateway' },
      { label: 'Direct Trail Access', sub: '5 marked trekking routes' },
      { label: 'Mountain Bike Fleet', sub: 'Trek bikes with helmets included' },
      { label: 'Riverside Bouldering', sub: 'Certified adventure guides' },
    ],
    gallery: [
      '/assets/images/forestgate-image/TREKKING.png',
      '/assets/images/forestgate-image/ADVENTURE ACTIVITIES.jpg',
      '/assets/images/forestgate-image/POOLSIDE SUNSET PARTY.jpg',
      '/assets/images/forestgate-image/TRAVELLING.jpeg',
    ],
    features: [
      'Expedition Gear Room with Free Mountain Bikes & Trekking Poles',
      'Panoramic Riverside Cliff Swimming Pool & Deck',
      'Open-Air Stone BBQ Bar with Live Flame Grills',
      'Rock Climbing & Rope Course Zone for Kids & Adults',
      'Sunset Valley Vista Amphitheater',
      'Secure Parking & EV Charging Stations',
    ],
    experiences: [
      {
        id: 'ridge-trek',
        title: 'Morni Ridge Summit Expedition',
        tag: 'Trekking',
        description:
          'A guided 7 km ascent along pine ridges offering 360-degree views stretching across Himachal and the plains below.',
        image: '/assets/images/forestgate-image/TREKKING.png',
        duration: '3.5 Hours',
        timing: '7:30 AM (Morning)',
      },
      {
        id: 'mountain-biking',
        title: 'Pine Forest Downhill Bike Safari',
        tag: 'Adrenaline',
        description:
          'Strap on your helmet and ride premium suspension mountain bikes across scenic hill village switchbacks and packed-earth forest trails.',
        image: '/assets/images/forestgate-image/ADVENTURE ACTIVITIES.jpg',
        duration: '2 Hours',
        timing: '10:00 AM & 4:00 PM',
      },
      {
        id: 'poolside-sunset',
        title: 'Sunset Pool Barbecue & Tropical Cocktails',
        tag: 'Social',
        description:
          'Relax by the cliffside pool with chilled mocktails, live barbecue skewers, and energetic lounge beats as the mountain sky turns violet.',
        image: '/assets/images/forestgate-image/POOLSIDE SUNSET PARTY.jpg',
        duration: 'Evening Session',
        timing: '5:30 PM - 8:30 PM',
      },
      {
        id: 'riverside-boulder',
        title: 'Riverside Scrambling & Natural Spring Dip',
        tag: 'Wild Swim',
        description:
          'A thrilling scramble down to natural crystalline pools fed by Morni springs for a refreshing swim in untamed nature.',
        image: '/assets/images/forestgate-image/RIVER VIEW.jpeg',
        duration: '2.5 Hours',
        timing: 'Midday (11:00 AM)',
      },
    ],
    accommodations: [
      {
        name: 'The Trailblazer Family Lodge',
        type: 'Expedition Quad Villa',
        size: '1,300 sq.ft.',
        occupancy: 'Up to 5 Adults',
        price: '₹16,500',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Spacious stone lodge with direct trailhead access, secure sports gear lockers, outdoor wash-down area, and wide sundeck.',
        amenities: ['Direct Trail Access', 'Gear Lockers', 'Double Rain Shower', 'Smart TV with Streaming', 'Espresso Machine'],
      },
      {
        name: 'The River Ridge Cottage',
        type: 'Adventure Balcony Suite',
        size: '780 sq.ft.',
        occupancy: '2 Adults',
        price: '₹13,000',
        image: '/assets/images/forestgate-image/ROOM 1.jpeg',
        desc: 'Overlooking the gorge and river valley with a hammock terrace, king bed, and floor-to-ceiling glass doors that welcome fresh hill breezes.',
        amenities: ['Private Hammock Deck', 'Gorge & River Views', 'Plush Bedding', 'Fast Wi-Fi', 'Complimentary Breakfast'],
      },
    ],
    faqs: [
      {
        q: 'Are adventure activities at Nature’s Gate safe for beginners?',
        a: 'Yes, all activities are rated by difficulty and led by certified local guides with complete safety briefings, helmets, harness equipment, and first-aid kits.',
      },
      {
        q: 'Do you provide trekking equipment and mountain bikes?',
        a: 'Yes, Trek and Scott mountain bikes, trekking poles, daypacks, and water bottles are available complimentary for all staying guests at Nature’s Gate.',
      },
      {
        q: 'Can non-adventure travelers still enjoy Nature’s Gate?',
        a: 'Absolutely! Nature’s Gate features our signature cliffside swimming pool, sunset barbecue deck, soothing yoga pavilion, and peaceful valley view cottages.',
      },
    ],
  },
  {
    id: 'the-green-escape',
    slug: 'the-green-escape',
    href: '/the-green-escape',
    name: 'The Green Escape',
    tagline: 'Verdant Valley Hideaway, Organic Dining & Forest Solitude',
    badge: 'Verdant Valley Hideaway',
    elevation: '4,300 Ft.',
    temperature: '18°C - 24°C Year-Round Average',
    coverImage: '/assets/images/forestgate-image/Open Sky Dining.png',
    summary:
      'An emerald valley hideaway dedicated to organic farm-to-fork gastronomy, tranquil herbal gardens, digital detox, and deep restorative sleep.',
    overview:
      'The Green Escape is where sustainable luxury blooms. Set in a fertile micro-valley sheltered by lush evergreen ridges, this sanctuary showcases organic fruit orchards, zero-waste permaculture gardens, and open-sky dining terraces where every meal is an homage to local Himalayan terroir.',
    highlights: [
      { label: '4,300 Ft. Elevation', sub: 'Lush micro-climate valley' },
      { label: '100% Organic Kitchen', sub: 'Picked fresh from on-site gardens' },
      { label: 'Aromatherapy Gardens', sub: 'Lavender, Rosemary & Wild Mint' },
      { label: 'Digital Detox Haven', sub: 'Unplug and reconnect with nature' },
    ],
    gallery: [
      '/assets/images/forestgate-image/Open Sky Dining.png',
      '/assets/images/forestgate-image/Indoor&OutdoorGames.png',
      '/assets/images/forestgate-image/EXTRA.png',
      '/assets/images/forestgate-image/MOUNTAIN.png',
    ],
    features: [
      'Farm-to-Fork Open Sky Kitchen & Woodfired Pizza Oven',
      'Organic Herbal Tea Garden & Apothecary Bar',
      'Silent Reading Pavilion with Panoramic Valley Glass',
      'Aromatherapy Steam & Forest Mud Bath Sanctuary',
      'Solar-Powered Eco Suites with Rainwater Harvesting',
      'Starlit Lawn Daybeds for Mindful Cloud Watching',
    ],
    experiences: [
      {
        id: 'farm-cooking',
        title: 'Organic Garden Harvest & Chef Masterclass',
        tag: 'Gastronomy',
        description:
          'Harvest heritage vegetables and hill herbs directly with our executive chef, followed by an interactive woodfired cooking masterclass.',
        image: '/assets/images/forestgate-image/Open Sky Dining.png',
        duration: '2 Hours',
        timing: '11:30 AM Daily',
      },
      {
        id: 'herbal-spa',
        title: 'Herbal Infusion & Mountain Bath Ritual',
        tag: 'Wellness',
        description:
          'Soak in deep outdoor tubs infused with freshly plucked mountain sage, chamomile, and Himalayan mineral salts overlooking the emerald valley.',
        image: '/assets/images/forestgate-image/BATHROOM.jpeg',
        duration: '1.5 Hours',
        timing: 'By Appointment',
      },
      {
        id: 'silent-walk',
        title: 'Mindful Silence Walk through Emerald Valley',
        tag: 'Mindfulness',
        description:
          'A morning walking meditation through dew-kissed orchards and pine trails, cultivating deep presence and clarity of mind.',
        image: '/assets/images/forestgate-image/mountain trekking.jpg',
        duration: '1 Hour',
        timing: 'Sunrise (6:45 AM)',
      },
      {
        id: 'open-dining',
        title: 'Moonlit Seven-Course Terroir Dinner',
        tag: 'Culinary Journey',
        description:
          'An intimate dining experience served on our open-sky terrace featuring seasonal mushrooms, hill cheeses, and wood-roasted pine delicacies.',
        image: '/assets/images/forestgate-image/Open Sky Dining.png',
        duration: '2.5 Hours',
        timing: '8:00 PM Onwards',
      },
    ],
    accommodations: [
      {
        name: 'The Orchard Harvest Chalet',
        type: 'Eco-Luxury Sustainable Villa',
        size: '1,350 sq.ft.',
        occupancy: 'Up to 4 Adults',
        price: '₹17,000',
        image: '/assets/images/forestgate-image/ROOMS.jpeg',
        desc: 'Crafted from sustainable clay, local stone, and polished timber with a private orchard terrace, outdoor copper soaking tub, and open fireplace.',
        amenities: ['Outdoor Copper Tub', 'Private Orchard Terrace', 'Organic Linen Bedding', 'Espresso & Herbal Bar', 'Fireplace'],
      },
      {
        name: 'The Emerald Valley Suite',
        type: 'Romantic Valley View Sanctuary',
        size: '800 sq.ft.',
        occupancy: '2 Adults',
        price: '₹13,500',
        image: '/assets/images/forestgate-image/ROOM 1.jpeg',
        desc: 'Floor-to-ceiling glass facing the morning sun with a private daybed, organic tea station, and spacious rainfall shower.',
        amenities: ['Panoramic Valley Glass', 'Private Daybed', 'Organic Herbal Tea Bar', 'Rainfall Shower', 'Wi-Fi'],
      },
    ],
    faqs: [
      {
        q: 'Is the food at The Green Escape purely organic?',
        a: 'Yes, over 80% of our vegetables, herbs, and dairy are sourced directly from our on-site polyhouses, local hill farmers, and certified regional organic cooperatives.',
      },
      {
        q: 'Can we request dietary accommodations (vegan, gluten-free, jain)?',
        a: 'Certainly! Our culinary team specializes in bespoke wellness dining and happily accommodates vegan, gluten-free, keto, and satvik/jain diets with prior notice.',
      },
      {
        q: 'Is high-speed Wi-Fi available for workcations at The Green Escape?',
        a: 'Yes, despite being an organic eco-retreat, we provide enterprise-grade Wi-Fi across all suites and garden pavilions for seamless workcation stays.',
      },
    ],
  },
];
